version: '{build}'
image: Visual Studio 2012

init:
  - git config --global core.autocrlf true
  
pull_requests:
  do_not_increment_build_number: true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

before_build:
  - cmd: dotnet restore
  
branches:
  only:
    - master
    
test: off
